name: 'Jingdong Default Project'
description: ''
recipe: 'jingdong'
stages:
  - name: '准备期'
    description: ''
    tasks:
      - name: '获取交易所上传的准备文件'
        description: ''
        steps:
          - name: '检查交易所是否上传文件至 FTP'
            description: ''
            job_id: "111"
      - name: '填写《产品发布文件》，并上传、校验'
        description: ''
        steps:
          - name: '上传《产品发布文件》'
            description: ''
            job_id: "121"
          - name: '检验文件内容与编码'
            description: ''
            job_id: "122"
          - name: '生成京东指定格式 txt'
            description: ''
            job_id: "123"
      - name: '生成《产品合同文件》'
        description: ''
        steps:
          - name: '批量生成产品合同'
            description: ''
            job_id: "131"
      - name: '发送给京东，等待确认'
        description: ''
        steps:
          - name: '发送，并等待确认'
            description: ''
            job_id: "141"
      - name: '为交易所提供相关文件'
        description: ''
        steps:
          - name: '填写《产品销售计划表》，并上传、校验'
            description: ''
            job_id: "151"
          - name: '生成《产品合同文件》'
            description: ''
            job_id: "152"
          - name: '发送给交易所，等待确认'
            description: ''
            job_id: "153"
  - name: '募集期'
    description: ''
    tasks:
      - name: '获取京东的《交易确认文件》，并检验'
        description: ''
        steps:
          - name: '获取京东上传的《交易确认文件》'
            description: ''
            job_id: "211"
          - name: '检验'
            description: ''
            job_id: "212"
      - name: '为交易所准备相关文件，并发送'
        description: ''
        steps:
          - name: '上传《产品销售表》'
            description: ''
            job_id: "221"
          - name: '检验文件内容与编码'
            description: ''
            job_id: "222"
          - name: '生成《客户明细销售表》'
            description: ''
            job_id: "223"
          - name: '发送，并等待确认'
            description: ''
            job_id: "224"
  - name: '起息日'
    description: ''
    tasks:
      - name: '为京东提供《交易试算文件》'
        description: ''
        steps:
          - name: '生成《交易试算文件》'
            description: ''
            job_id: "311"
          - name: '发送，并等待确认'
            description: ''
            job_id: "312"
          - name: '获取《交易试算结果文件》'
            description: ''
            job_id: "313"
      - name: '为京东提供《交易还款文件》'
        description: ''
        steps:
          - name: '生成《交易还款文件》'
            description: ''
            job_id: "321"
          - name: '发送，并等待确认'
            description: ''
            job_id: "322"
          - name: '获取《交易还款结果文件》'
            description: ''
            job_id: "323"
  - name: '到期日'
    description: ''
    tasks:
      - name: 'TODO'
        description: ''
        steps:
          - name: 'TODO'
            description: ''
            job_id: "312"


