name: 'Jingdong Default Project'
description: ''
stages:
  - name: '准备期'
    description: ''
    tasks:
      - name: '获取广交所上传的准备文件'
        description: ''
        steps:
          - name: '检查广交所是否上传文件至 FTP'
            description: ''
      - name: '填写《产品发布文件》，并上传、校验'
        description: ''
        steps:
          - name: '上传《产品发布文件》'
            description: ''
          - name: '检验文件内容与编码'
            description: ''
          - name: '生成京东指定格式 txt'
            description: ''
      - name: '生成《产品合同文件》'
        description: ''
        steps:
          - name: '批量生成产品合同'
            description: ''
      - name: '发送给京东，等待确认'
        description: ''
        steps:
          - name: '发送'
            description: ''
          - name: '京东确认'
            description: ''
      - name: '为广交所提供相关文件'
        description: ''
        steps:
          - name: '填写《产品销售计划表》，并上传、校验'
            description: ''
          - name: '生成《产品合同文件》'
            description: ''
          - name: '发送'
            description: ''
          - name: '广交所确认'
            description: ''
  - name: '募集期'
    description: ''
  - name: '起息日'
    description: ''
  - name: '到期日'
    description: ''


